In [1]:
Q1. What is a database? Differentiate between SQL and NoSQL databases.
Database:
A database is an organized collection of data, generally stored and accessed electronically. Databases are designed to manage, store, and retrieve data efficiently.

SQL Databases:

Schema: Fixed schema with predefined tables, columns, and data types.
Structure: Table-based, with rows and columns.
ACID Compliance: Strong adherence to ACID (Atomicity, Consistency, Isolation, Durability) properties.
Queries: Uses SQL (Structured Query Language) for defining and manipulating data.
Examples: MySQL, PostgreSQL, Oracle, MS SQL Server.
NoSQL Databases:

Schema: Dynamic schema, allowing for flexible data structures.
Structure: Various types, including document-based, key-value pairs, wide-column stores, and graph databases.
ACID Compliance: May not fully adhere to ACID properties; often follows BASE (Basically Available, Soft state, Eventual consistency) principles.
Queries: Uses a variety of query languages, often specific to the type of NoSQL database.
Examples: MongoDB, Cassandra, Redis, Neo4j.


Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.


DDL (Data Definition Language):
DDL is used to define and manage database schema objects such as tables, indexes, and relationships.
CREATE: Used to create database objects such as tables, indexes, and databases.
CREATE TABLE students (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    age INT
);
DROP: Used to delete existing database objects.
DROP TABLE students;
ALTER: Used to modify existing database objects.
ALTER TABLE students ADD COLUMN address VARCHAR(255);
TRUNCATE: Used to delete all rows from a table without removing the table structure.
TRUNCATE TABLE students;


Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

DML (Data Manipulation Language):
DML is used to manipulate data within database objects.
INSERT: Used to add new records to a table.
INSERT INTO students (id, name, age) VALUES (1, 'John Doe', 20);
UPDATE: Used to modify existing records in a table.
UPDATE students SET age = 21 WHERE id = 1;
DELETE: Used to remove records from a table
DELETE FROM students WHERE id = 1;

Q4. What is DQL? Explain SELECT with an example.
DQL (Data Query Language):
DQL is used to query the database to retrieve data.
SELECT: Used to retrieve data from one or more tables.
SELECT name, age FROM students WHERE age > 18;

Q5. Explain Primary Key and Foreign Key.
Primary Key: A primary key is a unique identifier for a record in a table. It ensures that each record can be uniquely identified.
CREATE TABLE students (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    age INT
);
Foreign Key: A foreign key is a field in one table that uniquely identifies a row of another table. It creates a relationship 
between two tables.
CREATE TABLE courses (
    course_id INT PRIMARY KEY,
    course_name VARCHAR(100)
);

CREATE TABLE enrollments (
    student_id INT,
    course_id INT,
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);
CREATE TABLE courses (
    course_id INT PRIMARY KEY,
    course_name VARCHAR(100)
);

CREATE TABLE enrollments (
    student_id INT,
    course_id INT,
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.
import mysql.connector

# Establish a connection to the database
connection = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

# Create a cursor object
cursor = connection.cursor()

# Execute a query
cursor.execute("SELECT * FROM students")

# Fetch all the rows
rows = cursor.fetchall()

for row in rows:
    print(row)

# Close the cursor and connection
cursor.close()
connection.close()



Q7. Give the order of execution of SQL clauses in an SQL query.
The order of execution of SQL clauses in a query is:

FROM: Determines the source table(s).
JOIN: Joins tables together based on conditions.
WHERE: Filters records based on specified conditions.
GROUP BY: Groups records with identical values in specified columns.
HAVING: Filters groups based on specified conditions.
SELECT: Specifies the columns to be returned.
DISTINCT: Removes duplicate rows from the result set.
ORDER BY: Sorts the result set based on specified columns.
LIMIT/OFFSET: Limits the number of rows returned and specifies the starting point.

SyntaxError: invalid syntax (1761031318.py, line 1)